name: launcher_icons_gui
description: Simple GUI for launcher icons preview.

version: 1.0.0+1

environment:
  sdk: ">2.9.0"
  flutter: ">1.21.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  auto_size_text: ^2.1.0
  community_material_icon: ^5.4.55
  cupertino_icons: ^1.0.0
  fdottedline: ^1.0.1
  file_picker_web: 1.0.2+1
  flutter_colorpicker: ^0.3.4
  flutter_dropzone: ^1.0.9
  get_it: ^4.0.4
  google_nav_bar: ^3.0.0
  image: ^2.1.14
  shared_preferences: ^0.5.10
  shared_preferences_web: ^0.1.2+7
  platform_info: ^2.0.1
  provider: ^4.3.2+2
  url_launcher_web: ^0.1.3+2
  url_launcher: ^5.5.3
  websafe_svg: ^1.1.4

dev_dependencies:
  pedantic: any
  # flutter_test:
  #   sdk: flutter

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/platform_svgs/
