name: launcher_icons_gui
description: Simple GUI for launcher icons preview.

version: 1.0.0+1

environment:
  sdk: ">2.9.0"
  flutter: ">1.21.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_dropzone: ^1.0.9
  fdottedline: ^1.0.1
  platform_info: ^2.0.0
  file_picker_web: 1.0.2+1
  provider: ^4.3.2+1
  image: ^2.1.14
  get_it: ^4.0.4
  auto_size_text: ^2.1.0
  url_launcher_web: ^0.1.3+1
  url_launcher: ^5.5.2
  shared_preferences: ^0.5.10
  shared_preferences_web: ^0.1.2+7

dev_dependencies:
  pedantic: any
  # flutter_test:
  #   sdk: flutter

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
