name: launcher_icons_gui
description: Simple GUI for launcher icons preview.

version: 1.0.0+1

environment:
  sdk: ">2.9.0"
  flutter: ">1.21.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  flutter_dropzone: ^1.0.9
  fdottedline: ^1.0.1
  platform_info: ^2.0.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic: any
  # flutter_test:
  #   sdk: flutter

flutter_intl:
  enabled: true