name: launcher_icons_preview
description: Simple GUI for launcher icons preview.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <=2.12.0"
  flutter: ">=1.24.0-8.0"

dependencies:
  auto_size_text:
  community_material_icon:
  cupertino_icons: ^1.0.1+1
  desktop_window:
  fdottedline:
  file_picker_cross: ^4.2.6
  flutter:
    sdk: flutter
  flutter_colorpicker:
    git:
      url: git://github.com/mchome/flutter_colorpicker.git
  flutter_dropzone: ^1.0.9
  flutter_localizations:
    sdk: flutter
  get_it:
  google_nav_bar: ^3.1.0
  image_resizer:
  local_hero: ^0.1.0
  path_provider: ^1.6.24
  # permission_handler:
  platform_info: ^2.1.0
  provider:
  shared_preferences: ^0.5.12+4
  universal_html:
  url_launcher:
  websafe_svg: ^1.1.4

dependency_overrides:
  file_picker:
  flutter_dropzone_web:
  image:
  package_info:

dev_dependencies:
  pedantic:

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
