name: launcher_icons_preview
description: Simple GUI for launcher icons preview.

version: 1.0.0+1

environment:
  sdk: ">2.10.0"
  flutter: ">1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_colorpicker:
    git:
      url: git://github.com/mchome/flutter_colorpicker.git
  auto_size_text: ^2.1.0
  community_material_icon: ^5.4.55
  cupertino_icons: ^1.0.0
  fdottedline: ^1.0.1
  file_picker_cross: ^4.2.5
  flutter_dropzone: ^1.0.9
  get_it: ^5.0.1
  google_nav_bar: ^3.1.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  image_resizer: ^1.0.2
  local_hero: ^0.1.0
  path_provider: ^1.6.21
  path_provider_macos: ^0.0.4+4
  platform_info: ^2.1.0
  provider: ^4.3.2+2
  universal_html: ^1.2.3
  url_launcher: ^5.7.5
  url_launcher_web: ^0.1.4+1
  websafe_svg: ^1.1.4
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  build_runner: any
  hive_generator: any
  pedantic: any

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/platform_svgs/
