name: launcher_icons_gui
description: Simple GUI for launcher icons preview.

version: 1.0.0+1

environment:
  sdk: ">2.9.0"
  flutter: ">1.20.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic: any
  # flutter_test:
  #   sdk: flutter

flutter_intl:
  enabled: true