name: launcher_icons_preview
description: Simple GUI for launcher icons preview.

version: 1.0.0+1

environment:
  sdk: ">=2.11.9"
  flutter: ">=1.24.0-8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_colorpicker:
    git:
      url: git://github.com/mchome/flutter_colorpicker.git
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  auto_size_text: any
  community_material_icon: any
  cupertino_icons: ^1.0.1
  fdottedline: any
  file_picker_cross: ^4.2.6
  flutter_dropzone: ^1.0.9
  get_it: any
  google_nav_bar: ^3.1.0
  image_resizer: any
  local_hero: ^0.1.0
  path_provider: ^1.6.24
  path_provider_macos: ^0.0.4+6
  platform_info: ^2.1.0
  provider: any
  shared_preferences: ^0.5.12+4
  universal_html: any
  url_launcher: any
  websafe_svg: ^1.1.4

dependency_overrides:
  file_picker: ^2.0.13
  flutter_dropzone_web: ^1.0.9
  image: ^2.1.19
  package_info: ^0.4.3+2

dev_dependencies:
  pedantic: any

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
