name: launcher_icons_gui
description: Simple GUI for launcher icons preview.

version: 1.0.0+1

environment:
  sdk: ">2.10.0"
  flutter: ">1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^2.0.13
  auto_size_text: ^2.1.0
  community_material_icon: ^5.4.55
  cupertino_icons: ^1.0.0
  fdottedline: ^1.0.1
  file_picker: ^2.0.7
  flutter_colorpicker: ^0.3.4
  flutter_dropzone: ^1.0.9
  get_it: ^5.0.1
  google_nav_bar: ^3.0.2
  image: ^2.1.18
  local_hero: ^0.1.0
  platform_info: ^2.0.1
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12
  shared_preferences_web: ^0.1.2+7
  url_launcher: ^5.7.2
  url_launcher_web: ^0.1.4+1
  websafe_svg: ^1.1.4

dev_dependencies:
  pedantic: any

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/platform_svgs/
