name: launcher_icons_preview
description: Simple GUI for launcher/desktop app icons generation and preview.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <=2.12.0"
  flutter: ">=1.22.0"

dependencies:
  community_material_icon:
  cupertino_icons: ^1.0.1+1
  dotted_border:
  file_picker_cross: ^4.2.6
  flutter:
    sdk: flutter
  flutter_colorpicker:
# Waitng for my PR publish.
    git:
      url: git://github.com/mchome/flutter_colorpicker.git
  flutter_dropzone: ^1.0.9
  flutter_localizations:
    sdk: flutter
  get_it:
  google_nav_bar:
# Waitng for my PR reviewed.
    git:
      url: git://github.com/tsinis/google_nav_bar.git
  image_resizer:
  local_hero: ^0.1.0
  path_provider: ^1.6.24
  # permission_handler:
  platform_info: ^2.2.0
  provider:
  shared_preferences: ^0.5.12+4
  universal_html:
  url_launcher:
  websafe_svg: ^1.1.4
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dependency_overrides:
  file_picker:
  flutter_dropzone_web:
  image:
  package_info:

dev_dependencies:
  pedantic:

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
